// <auto-generated />
using System;
using Director.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Director.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260805082444_AddAutonomousGeneration")]
    partial class AddAutonomousGeneration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Director.Models.AutonomousGenerationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<bool>("CancellationRequested")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompletedSceneCount")
                        .HasColumnType("int");

                    b.Property<string>("ConfigurationSnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("CurrentSceneId")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentSceneNumber")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStage")
                        .HasColumnType("int");

                    b.Property<int>("FilmProjectId")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastHeartbeatAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OverallProgressPercentage")
                        .HasColumnType("float");

                    b.Property<double>("StageProgressPercentage")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalSceneCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CurrentSceneId");

                    b.HasIndex("FilmProjectId");

                    b.HasIndex("FilmProjectId", "Status")
                        .IsUnique()
                        .HasFilter("[Status] IN (0, 1, 2, 3, 4, 5, 6, 7, 10, 12)");

                    b.ToTable("AutonomousGenerationRuns");
                });

            modelBuilder.Entity("Director.Models.AutonomousSceneWorkItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AudioAttemptCount")
                        .HasColumnType("int");

                    b.Property<int?>("AudioMediaAssetId")
                        .HasColumnType("int");

                    b.Property<int>("AudioStatus")
                        .HasColumnType("int");

                    b.Property<int>("AutonomousGenerationRunId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("FinalizationStatus")
                        .HasColumnType("int");

                    b.Property<int>("ImageAttemptCount")
                        .HasColumnType("int");

                    b.Property<int?>("ImageMediaAssetId")
                        .HasColumnType("int");

                    b.Property<int>("ImageStatus")
                        .HasColumnType("int");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SceneNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("StorySceneId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("VideoAttemptCount")
                        .HasColumnType("int");

                    b.Property<int?>("VideoMediaAssetId")
                        .HasColumnType("int");

                    b.Property<int>("VideoStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AudioMediaAssetId");

                    b.HasIndex("ImageMediaAssetId");

                    b.HasIndex("VideoMediaAssetId");

                    b.HasIndex("AutonomousGenerationRunId", "SceneNumber")
                        .IsUnique();

                    b.HasIndex("StorySceneId", "AudioStatus");

                    b.HasIndex("StorySceneId", "AutonomousGenerationRunId")
                        .IsUnique();

                    b.HasIndex("StorySceneId", "ImageStatus");

                    b.HasIndex("StorySceneId", "VideoStatus");

                    b.ToTable("AutonomousSceneWorkItems");
                });

            modelBuilder.Entity("Director.Models.CharacterVoiceProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("CfgScale")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("DoSample")
                        .HasColumnType("bit");

                    b.Property<string>("EmotionStyle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("FilmProjectId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNarrator")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("MaxNewTokens")
                        .HasColumnType("int");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<int?>("Seed")
                        .HasColumnType("int");

                    b.Property<string>("SettingsHash")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)");

                    b.Property<double>("SpeakingRate")
                        .HasColumnType("float");

                    b.Property<int?>("StoryCharacterId")
                        .HasColumnType("int");

                    b.Property<double?>("Temperature")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UseEmotionStyling")
                        .HasColumnType("bit");

                    b.Property<string>("VoicePresetDisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VoicePresetKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.HasIndex("StoryCharacterId");

                    b.HasIndex("FilmProjectId", "IsNarrator", "IsDefault");

                    b.HasIndex("FilmProjectId", "StoryCharacterId", "IsDefault");

                    b.HasIndex("FilmProjectId", "StoryCharacterId", "IsDefault", "IsLocked")
                        .IsUnique()
                        .HasFilter("[StoryCharacterId] IS NOT NULL AND [IsDefault] = 1 AND [IsLocked] = 1");

                    b.ToTable("CharacterVoiceProfiles");
                });

            modelBuilder.Entity("Director.Models.FilmProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AspectRatio")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("CalculatedClipCount")
                        .HasColumnType("int");

                    b.Property<int>("ClipDurationSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MainCharacterDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NarratorTone")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("StoryGenre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetAudience")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalDurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UseNarrator")
                        .HasColumnType("bit");

                    b.Property<string>("VideoStyle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("VisualStyle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("FilmProjects");
                });

            modelBuilder.Entity("Director.Models.FilmScene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CharactersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContinuityFromPreviousScene")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DialogueJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("FilmProjectId")
                        .HasColumnType("int");

                    b.Property<int>("FilmStoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageNegativePrompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePrompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NarrationText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SceneDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SceneNumber")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StoryBeat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeOfDay")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValidationChecklistJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoNegativePrompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoPrompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FilmStoryId");

                    b.HasIndex("FilmProjectId", "SceneNumber")
                        .IsUnique();

                    b.ToTable("FilmScenes");
                });

            modelBuilder.Entity("Director.Models.FilmStory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClimaxSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContinuityRulesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DevelopmentSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndingSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FilmProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Logline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisualDirection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorldDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FilmProjectId")
                        .IsUnique();

                    b.ToTable("FilmStories");
                });

            modelBuilder.Entity("Director.Models.GenerationJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelRequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CurrentPhase")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int?>("CurrentStep")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalJobId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("FilmProjectId")
                        .HasColumnType("int");

                    b.Property<int>("MediaType")
                        .HasColumnType("int");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("NegativePrompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProgressPercentage")
                        .HasColumnType("float");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromptPreparationModel")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime?>("PromptPreparedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.Property<string>("SettingsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SourceMediaAssetId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TotalSteps")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExternalJobId");

                    b.HasIndex("FilmProjectId");

                    b.HasIndex("SourceMediaAssetId");

                    b.HasIndex("SceneId", "MediaType", "Status");

                    b.ToTable("GenerationJobs");
                });

            modelBuilder.Entity("Director.Models.LtxNativeVoiceProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccentDescription")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("FilmProjectId")
                        .HasColumnType("int");

                    b.Property<string>("GenderPresentation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PerceivedAge")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PitchDescription")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SettingsHash")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)");

                    b.Property<string>("SpeakingStyle")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("StoryCharacterId")
                        .HasColumnType("int");

                    b.Property<string>("TempoDescription")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VoiceDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StoryCharacterId");

                    b.HasIndex("FilmProjectId", "StoryCharacterId")
                        .IsUnique();

                    b.ToTable("LtxNativeVoiceProfiles");
                });

            modelBuilder.Entity("Director.Models.SceneMediaAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("float");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("FilmProjectId")
                        .HasColumnType("int");

                    b.Property<double?>("Fps")
                        .HasColumnType("float");

                    b.Property<int?>("FrameCount")
                        .HasColumnType("int");

                    b.Property<int>("GenerationJobId")
                        .HasColumnType("int");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<int>("MediaType")
                        .HasColumnType("int");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.Property<int?>("Seed")
                        .HasColumnType("int");

                    b.Property<int?>("SourceMediaAssetId")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FilmProjectId");

                    b.HasIndex("GenerationJobId");

                    b.HasIndex("SourceMediaAssetId");

                    b.HasIndex("SceneId", "MediaType", "IsSelected");

                    b.ToTable("SceneMediaAssets");
                });

            modelBuilder.Entity("Director.Models.SceneSpeechPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("FilmProjectId")
                        .HasColumnType("int");

                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TargetDurationSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FilmProjectId");

                    b.HasIndex("SceneId")
                        .IsUnique();

                    b.ToTable("SceneSpeechPlans");
                });

            modelBuilder.Entity("Director.Models.SceneSpeechSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("ActualDurationSeconds")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Emotion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SceneSpeechPlanId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpeakerKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SpeakerType")
                        .HasColumnType("int");

                    b.Property<double>("StartTimeSeconds")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("StoryCharacterId")
                        .HasColumnType("int");

                    b.Property<double>("TargetDurationSeconds")
                        .HasColumnType("float");

                    b.Property<string>("TurkishText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VoiceProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoryCharacterId");

                    b.HasIndex("VoiceProfileId");

                    b.HasIndex("SceneSpeechPlanId", "SortOrder");

                    b.ToTable("SceneSpeechSegments");
                });

            modelBuilder.Entity("Director.Models.StoryCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CharacterKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ClothingDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContinuityDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FilmStoryId")
                        .HasColumnType("int");

                    b.Property<string>("ForbiddenChangesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("PersonalityDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhysicalDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("VoiceDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FilmStoryId", "CharacterKey")
                        .IsUnique();

                    b.ToTable("StoryCharacters");
                });

            modelBuilder.Entity("Director.Models.AutonomousGenerationRun", b =>
                {
                    b.HasOne("Director.Models.FilmScene", "CurrentScene")
                        .WithMany()
                        .HasForeignKey("CurrentSceneId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Director.Models.FilmProject", "FilmProject")
                        .WithMany("AutonomousGenerationRuns")
                        .HasForeignKey("FilmProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentScene");

                    b.Navigation("FilmProject");
                });

            modelBuilder.Entity("Director.Models.AutonomousSceneWorkItem", b =>
                {
                    b.HasOne("Director.Models.SceneMediaAsset", "AudioMediaAsset")
                        .WithMany()
                        .HasForeignKey("AudioMediaAssetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Director.Models.AutonomousGenerationRun", "AutonomousGenerationRun")
                        .WithMany("WorkItems")
                        .HasForeignKey("AutonomousGenerationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Director.Models.SceneMediaAsset", "ImageMediaAsset")
                        .WithMany()
                        .HasForeignKey("ImageMediaAssetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Director.Models.FilmScene", "StoryScene")
                        .WithMany()
                        .HasForeignKey("StorySceneId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Director.Models.SceneMediaAsset", "VideoMediaAsset")
                        .WithMany()
                        .HasForeignKey("VideoMediaAssetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AudioMediaAsset");

                    b.Navigation("AutonomousGenerationRun");

                    b.Navigation("ImageMediaAsset");

                    b.Navigation("StoryScene");

                    b.Navigation("VideoMediaAsset");
                });

            modelBuilder.Entity("Director.Models.CharacterVoiceProfile", b =>
                {
                    b.HasOne("Director.Models.FilmProject", "FilmProject")
                        .WithMany()
                        .HasForeignKey("FilmProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Director.Models.StoryCharacter", "StoryCharacter")
                        .WithMany()
                        .HasForeignKey("StoryCharacterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FilmProject");

                    b.Navigation("StoryCharacter");
                });

            modelBuilder.Entity("Director.Models.FilmScene", b =>
                {
                    b.HasOne("Director.Models.FilmProject", "FilmProject")
                        .WithMany("Scenes")
                        .HasForeignKey("FilmProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Director.Models.FilmStory", "FilmStory")
                        .WithMany("Scenes")
                        .HasForeignKey("FilmStoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilmProject");

                    b.Navigation("FilmStory");
                });

            modelBuilder.Entity("Director.Models.FilmStory", b =>
                {
                    b.HasOne("Director.Models.FilmProject", "FilmProject")
                        .WithOne("Story")
                        .HasForeignKey("Director.Models.FilmStory", "FilmProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilmProject");
                });

            modelBuilder.Entity("Director.Models.GenerationJob", b =>
                {
                    b.HasOne("Director.Models.FilmProject", "FilmProject")
                        .WithMany("GenerationJobs")
                        .HasForeignKey("FilmProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Director.Models.FilmScene", "Scene")
                        .WithMany("GenerationJobs")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Director.Models.SceneMediaAsset", "SourceMediaAsset")
                        .WithMany()
                        .HasForeignKey("SourceMediaAssetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FilmProject");

                    b.Navigation("Scene");

                    b.Navigation("SourceMediaAsset");
                });

            modelBuilder.Entity("Director.Models.LtxNativeVoiceProfile", b =>
                {
                    b.HasOne("Director.Models.FilmProject", "FilmProject")
                        .WithMany()
                        .HasForeignKey("FilmProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Director.Models.StoryCharacter", "StoryCharacter")
                        .WithMany()
                        .HasForeignKey("StoryCharacterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FilmProject");

                    b.Navigation("StoryCharacter");
                });

            modelBuilder.Entity("Director.Models.SceneMediaAsset", b =>
                {
                    b.HasOne("Director.Models.FilmProject", "FilmProject")
                        .WithMany("MediaAssets")
                        .HasForeignKey("FilmProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Director.Models.GenerationJob", "GenerationJob")
                        .WithMany("Assets")
                        .HasForeignKey("GenerationJobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Director.Models.FilmScene", "Scene")
                        .WithMany("MediaAssets")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Director.Models.SceneMediaAsset", "SourceMediaAsset")
                        .WithMany()
                        .HasForeignKey("SourceMediaAssetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FilmProject");

                    b.Navigation("GenerationJob");

                    b.Navigation("Scene");

                    b.Navigation("SourceMediaAsset");
                });

            modelBuilder.Entity("Director.Models.SceneSpeechPlan", b =>
                {
                    b.HasOne("Director.Models.FilmProject", "FilmProject")
                        .WithMany()
                        .HasForeignKey("FilmProjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Director.Models.FilmScene", "Scene")
                        .WithOne()
                        .HasForeignKey("Director.Models.SceneSpeechPlan", "SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilmProject");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Director.Models.SceneSpeechSegment", b =>
                {
                    b.HasOne("Director.Models.SceneSpeechPlan", "SceneSpeechPlan")
                        .WithMany("Segments")
                        .HasForeignKey("SceneSpeechPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Director.Models.StoryCharacter", "StoryCharacter")
                        .WithMany()
                        .HasForeignKey("StoryCharacterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Director.Models.CharacterVoiceProfile", "VoiceProfile")
                        .WithMany()
                        .HasForeignKey("VoiceProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SceneSpeechPlan");

                    b.Navigation("StoryCharacter");

                    b.Navigation("VoiceProfile");
                });

            modelBuilder.Entity("Director.Models.StoryCharacter", b =>
                {
                    b.HasOne("Director.Models.FilmStory", "FilmStory")
                        .WithMany("Characters")
                        .HasForeignKey("FilmStoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilmStory");
                });

            modelBuilder.Entity("Director.Models.AutonomousGenerationRun", b =>
                {
                    b.Navigation("WorkItems");
                });

            modelBuilder.Entity("Director.Models.FilmProject", b =>
                {
                    b.Navigation("AutonomousGenerationRuns");

                    b.Navigation("GenerationJobs");

                    b.Navigation("MediaAssets");

                    b.Navigation("Scenes");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Director.Models.FilmScene", b =>
                {
                    b.Navigation("GenerationJobs");

                    b.Navigation("MediaAssets");
                });

            modelBuilder.Entity("Director.Models.FilmStory", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("Director.Models.GenerationJob", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("Director.Models.SceneSpeechPlan", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
